name: Build Tauri App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu, x86_64-apple-darwin
    
    - name: Install dependencies (Ubuntu)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-6.0-dev libgtk-4-dev libayatana-appindicator3-dev librsvg2-dev
    
    - name: Install dependencies (macOS)
      if: matrix.platform == 'macos-latest'
      run: |
        brew install node
        brew install rust
    
    - name: Install dependencies (Windows)
      if: matrix.platform == 'windows-latest'
      run: |
        rustup target add x86_64-pc-windows-msvc
    
    - name: Install frontend dependencies
      working-directory: tauri-app
      run: npm ci
    
    - name: Build frontend
      working-directory: tauri-app
      run: npm run build
    
    - name: Build Tauri app
      working-directory: tauri-app
      run: npm run tauri build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: instagrap-${{ matrix.platform }}
        path: tauri-app/src-tauri/target/release/bundle/
        retention-days: 30
